import type { CityConfig } from '@city-monitor/shared';

export const berlin: CityConfig = {
  id: 'berlin',
  name: 'Berlin',
  country: 'DE',
  coordinates: { lat: 52.52, lon: 13.405 },
  boundingBox: { north: 52.68, south: 52.34, east: 13.76, west: 13.09 },
  timezone: 'Europe/Berlin',
  languages: ['de', 'en', 'tr', 'ar'],
  map: {
    center: [13.405, 52.52],
    zoom: 11,
    minZoom: 9,
    maxZoom: 17,
    bounds: [
      [12.9, 52.3],
      [13.8, 52.7],
    ],
  },
  theme: { accent: '#E2001A' },
  feeds: [
    { name: 'rbb24', url: 'https://www.rbb24.de/aktuell/index.xml/feed=rbb24.xml', tier: 1, type: 'mainstream', lang: 'de' },
    { name: 'Tagesspiegel', url: 'https://www.tagesspiegel.de/contentexport/feed/home', tier: 1, type: 'mainstream', lang: 'de' },
    { name: 'Berliner Morgenpost', url: 'https://www.morgenpost.de/berlin/rss', tier: 2, type: 'mainstream', lang: 'de' },
    { name: 'BZ Berlin', url: 'https://www.bz-berlin.de/feed', tier: 2, type: 'mainstream', lang: 'de' },
    { name: 'Berliner Zeitung', url: 'https://www.berliner-zeitung.de/feed.xml', tier: 2, type: 'mainstream', lang: 'de' },
    { name: 'taz Berlin', url: 'https://taz.de/Berlin/!p4610;rss/', tier: 2, type: 'mainstream', lang: 'de' },
    { name: 'Polizei Berlin', url: 'https://www.berlin.de/presse/pressemitteilungen/index/feed?institutions[]=Polizei+Berlin', tier: 1, type: 'gov', lang: 'de', category: 'crime' },
    { name: 'Gründerszene Berlin', url: 'https://www.businessinsider.de/gruenderszene/feed/', tier: 3, type: 'tech', lang: 'de' },
    { name: 'Exberliner', url: 'https://www.exberliner.com/feed/', tier: 3, type: 'other', lang: 'en' },
  ],
  dataSources: {
    weather: { provider: 'open-meteo', lat: 52.52, lon: 13.405 },
    transit: {
      provider: 'hafas',
      operatorId: 'VBB',
      endpoint: 'https://v6.vbb.transport.rest',
      stations: [
        { id: '900100003', name: 'Alexanderplatz' },
        { id: '900003201', name: 'Hauptbahnhof' },
        { id: '900120005', name: 'Zoologischer Garten' },
        { id: '900100001', name: 'Friedrichstraße' },
        { id: '900007102', name: 'Gesundbrunnen' },
        { id: '900120004', name: 'Ostkreuz' },
        { id: '900058101', name: 'Südkreuz' },
        { id: '900024101', name: 'Westkreuz' },
        { id: '900013101', name: 'Nollendorfplatz' },
        { id: '900017101', name: 'Mehringdamm' },
        { id: '900013102', name: 'Hermannplatz' },
        { id: '900029101', name: 'Spandau' },
      ],
    },
    airQuality: {
      sensorCommunityStations: [
        { sensorId: 25905, name: 'Spandau', fallbackIds: [828, 51034] },
        { sensorId: 5040, name: 'Reinickendorf', fallbackIds: [11957, 40765] },
        { sensorId: 57233, name: 'Tegel', fallbackIds: [2211, 88791] },
        { sensorId: 23322, name: 'Marzahn-Hellersdorf', fallbackIds: [87879, 43640] },
        { sensorId: 9409, name: 'Marzahn-Nord', fallbackIds: [13733, 18376] },
        { sensorId: 7051, name: 'Treptow-Köpenick', fallbackIds: [60516, 91390] },
        { sensorId: 81508, name: 'Grünau', fallbackIds: [95842, 52480] },
        { sensorId: 1376, name: 'Lichtenberg', fallbackIds: [83562, 44120] },
        { sensorId: 68686, name: 'Hohenschönhausen', fallbackIds: [9767, 84379] },
        { sensorId: 19095, name: 'Charlottenburg', fallbackIds: [93671, 50066] },
        { sensorId: 70607, name: 'Westend', fallbackIds: [12603, 47089] },
        { sensorId: 15536, name: 'Zehlendorf', fallbackIds: [26261, 97662] },
        { sensorId: 3036, name: 'Pankow', fallbackIds: [48036, 18814] },
        { sensorId: 80508, name: 'Französisch Buchholz', fallbackIds: [13090, 43626] },
      ],
    },
    events: [
      { source: 'kulturdaten', url: 'https://api-v2.kulturdaten.berlin/api/events' },
      { source: 'ticketmaster', url: 'https://app.ticketmaster.com/discovery/v2/events.json' },
      { source: 'gomus', url: 'https://smb.gomus.de/api/v4/events' },
    ],
    police: {
      provider: 'rss',
      url: 'https://www.berlin.de/presse/pressemitteilungen/index/feed?institutions[]=Polizei+Berlin',
      districts: [
        'Mitte', 'Friedrichshain', 'Kreuzberg', 'Pankow', 'Prenzlauer Berg',
        'Charlottenburg', 'Wilmersdorf', 'Spandau', 'Steglitz', 'Zehlendorf',
        'Tempelhof', 'Schöneberg', 'Neukölln', 'Treptow', 'Köpenick',
        'Marzahn', 'Hellersdorf', 'Lichtenberg', 'Reinickendorf', 'Wedding',
        'Moabit', 'Tiergarten',
      ],
    },
    nina: { ars: '110000000000' },
    roadworks: { url: 'https://api.viz.berlin.de/daten/baustellen_sperrungen.json' },
    waterLevels: {
      provider: 'pegelonline',
      stations: [
        { uuid: '09e15cf6-f155-4b76-b92f-6c260839121c', name: 'Mühlendamm', waterBody: 'Spree' },
        { uuid: 'd89eb759-58c4-43f4-9fe4-e6a21af23f5c', name: 'Charlottenburg', waterBody: 'Spree' },
        { uuid: '47d3e815-c556-4e1b-93de-9fe07329fb00', name: 'Köpenick', waterBody: 'Spree' },
        { uuid: '2c68509c-bf1e-4866-9ec4-b26b231e5e04', name: 'Spandau', waterBody: 'Havel' },
        { uuid: '6b595707-8c47-4bc7-a803-dbc327775c26', name: 'Schmöckwitz', waterBody: 'Dahme' },
      ],
    },
    budget: {
      provider: 'berlin-doppelhaushalt',
      csvUrl: 'https://www.berlin.de/sen/finanzen/service/daten/260223_doppelhaushalt_2026_2027.csv',
    },
    socialAtlas: {
      provider: 'mss-wfs',
      wfsUrl: 'https://gdi.berlin.de/services/wfs/mss_2023',
    },
    pollen: {
      provider: 'dwd',
      regionId: 50,         // Brandenburg und Berlin
      partregionId: -1,     // no sub-regions
    },
    noiseSensors: {
      provider: 'sensor-community',
      lat: 52.52,
      lon: 13.405,
      radius: 15,
    },
    appointments: {
      provider: 'service-berlin',
      services: [
        { id: '120686', name: 'Anmeldung' },
        { id: '121482', name: 'Personalausweis' },
        { id: '120335', name: 'Reisepass' },
        { id: '120926', name: 'Führungszeugnis' },
        { id: '120702', name: 'Meldebescheinigung' },
        { id: '120697', name: 'Ummeldung' },
        { id: '121701', name: 'Beglaubigung' },
        { id: '121151', name: 'Kinderreisepass' },
        { id: '121627', name: 'Fahrerlaubnis' },
        { id: '121721', name: 'Bewohnerparkausweis' },
      ],
    },
    councilMeetings: {
      bvv: [
        { district: 'Mitte', baseUrl: 'https://www.sitzungsdienst-mitte.de/oi/oparl/1.0' },
        { district: 'Pankow', baseUrl: 'https://www.sitzungsdienst-pankow.de/oi/oparl/1.0' },
        { district: 'Charlottenburg-Wilmersdorf', baseUrl: 'https://www.sitzungsdienst-charlottenburg-wilmersdorf.de/oi/oparl/1.0' },
        { district: 'Friedrichshain-Kreuzberg', baseUrl: 'https://www.sitzungsdienst-friedrichshain-kreuzberg.de/oi/oparl/1.0' },
        { district: 'Neukölln', baseUrl: 'https://www.sitzungsdienst-neukoelln.de/oi/oparl/1.0' },
        { district: 'Steglitz-Zehlendorf', baseUrl: 'https://www.sitzungsdienst-steglitz-zehlendorf.de/oi/oparl/1.0' },
        { district: 'Treptow-Köpenick', baseUrl: 'https://www.sitzungsdienst-treptow-koepenick.de/oi/oparl/1.0' },
        { district: 'Marzahn-Hellersdorf', baseUrl: 'https://www.sitzungsdienst-marzahn-hellersdorf.de/oi/oparl/1.0' },
        { district: 'Lichtenberg', baseUrl: 'https://www.sitzungsdienst-lichtenberg.de/oi/oparl/1.0' },
        { district: 'Reinickendorf', baseUrl: 'https://www.sitzungsdienst-reinickendorf.de/oi/oparl/1.0' },
        { district: 'Tempelhof-Schöneberg', baseUrl: 'https://www.sitzungsdienst-tempelhof-schoeneberg.de/oi/oparl/1.0' },
      ],
      parliament: {
        committeeUrl: 'https://www.parlament-berlin.de/app_com.xml',
        plenaryUrl: 'https://www.parlament-berlin.de/app_plen.xml',
      },
    },
  },
};
